django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.defaults import patterns, url, include
from django.contrib import admin

handler500 = 'djangotoolbox.errorviews.server_error'

admin.autodiscover()

urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),
    (r'^accounts/register$', 'words.views.manage.user_registration'),
    
    (r'^lesson/list$', 'words.views.manage.lesson_list'),
    (r'^lesson/new$', 'words.views.manage.new_lesson'),
    (r'^lesson/(\d+)', 'words.views.manage.lesson_details'),
    
    (r'^question/new$', 'words.views.manage.question_new_tile'),
    (r'^question/(\d+)/details$', 'words.views.manage.question_details'),
    
    (r'^lesson/learn$', 'words.views.learn.learn'),
    (r'^lesson/learn/lesson/(?P<lesson_id>\d+)$', 'words.views.learn.learn', {}, "learn_lesson"),
    (r'^lesson/learn/days/(?P<days>\d+)$', 'words.views.learn.learn', {}, "learn_in_days"),
    (r'^lesson/repeat$', 'words.views.learn.repeat'),
    (r'^lesson/learn/ask$', 'words.views.learn.ask_question'),
    (r'^lesson/learn/check$', 'words.views.learn.check'),
    (r'^lesson/learn/score/(\d)$', 'words.views.learn.score'),
    
    (r'^tile/question/(\d+)/details$', 'words.views.manage.question_details_tile'),
    
    (r'^$', 'words.views.manage.index'),
)

urlpatterns += staticfiles_urlpatterns()

words/models.py
'''
Created on 22-09-2012

@author: pawel
'''
from django.contrib.auth.models import User
from django.db import models
from django.forms import CharField
from djangotoolbox.fields import ListField
import datetime
import math

class Lesson(models.Model):
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=255, blank=True) 
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(default = datetime.datetime.now)
    user = models.ForeignKey(User)
    active = models.BooleanField(default = True)
    
    def __unicode__(self):
        return u"{0}".format(self.name)
    
    def question_to_learn_count(self):
        midnight = midnight_x_days_further(0)
        return Question.objects.filter(next_repeat__lte=midnight, lesson = self.id).count()

    def question_count(self):
        return Question.objects.filter(lesson = self.id).count()
    
    def belongs_to_user(self, user):
        return self.user == user

class AnswerField(ListField):
    def formfield(self, **kwargs):
        return models.Field.formfield(self, CharField, **kwargs)

def midnight_x_days_further(days):
    now = datetime.datetime.now()
    return datetime.datetime(now.year, now.month, now.day) + datetime.timedelta(days=days + 1)

class QuestionManager(models.Manager):
    
    def get_question_to_learn_in_filter(self, user, days = 0, lesson_id = None):
        midnight = midnight_x_days_further(days)
    
        if days > 0:
            tomorrow_midnight = midnight + datetime.timedelta(days=1)
            return self.filter(active = True, next_repeat__lt=tomorrow_midnight, next_repeat__gte=midnight, lesson__in = self.get_user_lesson_ids(user, lesson_id))
        else:
            return self.filter(active = True, next_repeat__lte=midnight, lesson__in = self.get_user_lesson_ids(user, lesson_id))
    
    def to_learn_in_count(self, user, days = 0, lesson_id = None):
        return self.get_question_to_learn_in_filter(user, days, lesson_id).count()
    
    def to_learn_in(self, user, days = 0, lesson_id = None, max_count = 50):
        return (self.get_question_to_learn_in_filter(user, days, lesson_id))[0:max_count]
        
    def to_repeat(self, user):
        return self.get_to_repeat_filter(user)
    
    def to_repeat_count(self, user):
        return self.get_to_repeat_filter(user).count()
    
    def get_to_repeat_filter(self, user, lesson_id = None):
        return self.filter(to_repeat=True, lesson__in = self.get_user_lesson_ids(user, lesson_id))
    
    def get_user_lesson_ids(self, user, lesson_id = None, only_active = True):
        if lesson_id:
            lesson = Lesson.objects.get(id = lesson_id)
            if only_active and not lesson.active:
                lesson = None
            
            if lesson and lesson.user == user:
                lesson_ids = [lesson_id]
            else:
                lesson_ids = []
        else: 
            if only_active:
                lessons = Lesson.objects.filter(user = user, active = True)
            else:
                lessons = Lesson.objects.filter(user = user)
                
            lesson_ids = map((lambda lesson: lesson.id), lessons)
        
        return lesson_ids
    
class Question(models.Model):
    objects = QuestionManager()
    
    question = models.CharField(max_length=1024)
    tip = models.CharField(max_length=1024, blank=True)
    answer_tip = models.CharField(max_length=1024, blank=True)
    image_url = models.URLField(blank=True)
    answer_image_url = models.URLField(blank=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(default = datetime.datetime.now)
    level = models.IntegerField()
    next_repeat = models.DateTimeField()
    to_repeat = models.BooleanField()
    e_factor = models.FloatField(default=2.5)
    lesson = models.ForeignKey(Lesson)
    last_attempt_date = models.DateTimeField(blank=True,null=True)
    active = models.BooleanField(default=True)
    
    def answers(self):
        return Answer.objects.filter(question=self)
    
    def score(self, score):
        ci = self.current_iteration()
        
        if score == 0:
            ci.answers_0 = (ci.answers_0+1)
        elif score == 1:
            ci.answers_1 = (ci.answers_1+1)
        elif score == 2:
            ci.answers_2 = (ci.answers_2+1)
        elif score == 3:
            ci.answers_3 = (ci.answers_3+1)
        elif score == 4:
            ci.answers_4 = (ci.answers_4+1)
        elif score == 5:
            ci.answers_5 = (ci.answers_5+1)

        if score < 3:
            self.level = 1
            self.next_repeat = datetime.datetime.now() + datetime.timedelta(days=self.current_iteration().day_interval)
        else:
            ci.learning_finished = datetime.datetime.now()
            
            #EF+(0.1-(5-q)*(0.08+(5-q)*0.02))
            self.e_factor = self.e_factor + (0.1 - (5 - score) * (0.08 + (5 - score) * 0.02))

            if self.e_factor < 1.3:
                self.e_factor = 1.3
        
            ni = self.next_iteration(ci)
        
            self.next_repeat = datetime.datetime.now() + datetime.timedelta(days=ni.day_interval)
            
        if score < 4:
            self.to_repeat = True
        
        self.last_attempt_date = datetime.datetime.now()
        
        ci.save()
        
        self.save()
        
    def iterations(self):
        return Iteration.objects.filter(question=self)
        
    def current_iteration(self):
        candidates = Iteration.objects.filter(question=self, level=self.level)
        if len(candidates) > 0:
            return candidates[0]
        else:
            ret = self.create_iteration()
            return ret
        
    def create_iteration(self):
        ret = Iteration()
        
        ret.question = self
        ret.level = self.level
        ret.learning_begin = datetime.datetime.now()
        ret.created_at = datetime.datetime.now()
        ret.answers_0 = 0
        ret.answers_1 = 0
        ret.answers_2 = 0
        ret.answers_3 = 0
        ret.answers_4 = 0
        ret.answers_5 = 0    
        ret.day_interval = 1
        
        ret.save()
        
        return ret

    def next_iteration(self, last_iteration):
        self.level = self.level +1
        
        if self.level > 9:
            self.active = False
        
        ret = None
        
        candidates = Iteration.objects.filter(question=self, level=self.level)
        if len(candidates) > 0:
            ret = candidates[0]
        else:
            ret = self.create_iteration()
        
        if ret.level == 1:
            ret.day_interval = 1
        elif ret.level == 2:
            ret.day_interval = 4
        else:
            ret.day_interval = math.floor(self.e_factor * last_iteration.day_interval)
        
        ret.save()
            
        return ret
    
    def repeated(self, score):
        if score > 3:
            self.to_repeat = False
            self.save()
    
    def __unicode__(self):
        return u"{0}".format(self.question)
    
class Iteration(models.Model):
    question = models.ForeignKey(Question)
    level = models.IntegerField()
    learning_begin = models.DateTimeField()
    day_interval = models.IntegerField(default = 4)
    answers_0 = models.IntegerField()
    answers_1 = models.IntegerField()
    answers_2 = models.IntegerField()
    answers_3 = models.IntegerField()
    answers_4 = models.IntegerField()
    answers_5 = models.IntegerField()
    learning_finished = models.DateTimeField(blank=True,null=True)
    created_at = models.DateTimeField(default = datetime.datetime.now)
    updated_at = models.DateTimeField(default = datetime.datetime.now)
    
    def __unicode__(self):
        return u"Level {0} for {1}".format(self.level, self.question)
    
    def save(self):
        if not self.created_at:
            self.created_at = datetime.datetime.now()
        
        self.updated_at = datetime.datetime.now()
        super(Iteration, self).save()
    
class Answer(models.Model):
    answer = models.CharField(max_length=1024)
    tip = models.CharField(max_length=1024)
    question = models.ForeignKey(Question)
    created_at = models.DateTimeField(default = datetime.datetime.now)
    updated_at = models.DateTimeField(default = datetime.datetime.now)

    def save(self):
        if not self.created_at:
            self.created_at = datetime.datetime.now()
            
        self.updated_at = datetime.datetime.now()
        super(Answer, self).save()
    
    def __unicode__(self):
        return "{0}".format(self.answer)

    
    

words/views.py
'''
Created on 22-09-2012

@author: pawel
'''

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from forms import UserCreationForm
from words.forms import LessonForm, QuestionForm
from words.models import Lesson, Question
from django.core.urlresolvers import reverse
from django.http import HttpResponseServerError

@login_required
def index(request):
    to_learn_list = []
    
    for idx in range(10):
        days_from = "today"
        if idx == 1:
            days_from = "1 day"
        elif idx > 1:
            days_from = "{0} days".format(idx)
        
        to_learn_list.append([days_from, Question.objects.to_learn_in(idx).count()])
        
    return render(request, "index.html", {"to_learn_list": to_learn_list})

def user_registration(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save(True)
            return redirect("words.views.index")
    else:
        form = UserCreationForm()
        
    return render(request, "registration/registration.html", {'form': form})

@login_required
def lesson_list(request):
    lessons = Lesson.objects.filter(user = request.user)
    return render(request, "words/lesson_list.html", {'lessons': lessons})

@login_required
def lesson_details(request, lesson_id):
    lesson = Lesson.objects.get(user = request.user, id = lesson_id)
    request.session["lesson_id"] = lesson.id
    
    questions = Question.objects.filter(lesson = lesson)
    
    return render(request, "words/lesson_details.html", {'lesson': lesson, 'questions': questions})

@login_required
def new_lesson(request):
    if request.method == "POST":
        form = LessonForm(request.user, request.POST)
        if form.is_valid():
            form.save(True)
            return redirect("words.views.lesson_list")
    else:
        form = LessonForm(request.user)
        
    return render(request, "words/lesson_form.html", {'form': form})

@login_required
def question_new_tile(request):
    lesson = fetch_lesson_from_session(request)
    if lesson == None:
        return redirect(reverse("words.views.lesson_list"))
    
    if request.method == "POST":
        form = QuestionForm(lesson, request.POST)
        
        if form.is_valid():
            saved_queston =  form.save(True)
            return redirect("words.views.question_details_tile", saved_queston.id)
    else:
        form = QuestionForm(lesson)
        
    return render(request, "words/question_form_tile.html", {'form': form})

def fetch_lesson_from_session(request):
    lesson_id = request.session.get("lesson_id", None)
    if lesson_id == None:
        return None
    
    return Lesson.objects.get(id = lesson_id)

@login_required
def question_details_tile(request, question_id):
    lesson = fetch_lesson_from_session(request)
    if lesson == None:
        return HttpResponseServerError()
    
    question = Question.objects.get(lesson = lesson, id = question_id)
    
    return render(request, "words/question_details_tile.html", {'question': question})

@login_required
def learn(request):
    questions_to_learn = Question.objects.to_learn_in(0)
    learning_bunch = LearningBunch(questions_to_learn)
    
    request.session['learning_bunch'] = learning_bunch
    
    return render(request, "words/learn.html", {'learning_bunch': learning_bunch})

@login_required
def ask_question(request):
    learning_bunch = request.session.get('learning_bunch', None)
    question = learning_bunch.current_question()
    
    return render(request, "words/next_question.html", {'learning_bunch': learning_bunch, 'question': question})

class LearningBunch:
    
    def __init__(self, questions_to_learn):
        self.bunch = len(questions_to_learn)
        self.passed = 0
        self.current = 0
        
        self.items = []
        for question in questions_to_learn:
            self.items.append(LearningItem(question))
            
    def current_question(self):
        return self.items[self.current]
    
    def __repr__(self):
        return "Learning bund of {0} questions.".format(self.bunch)
            
class LearningItem:
    
    def __init__(self, question):
        self.question = question
        self.score = 0
    
    def __repr__(self):
        return "Question to ask of score {1}: {0}".format(self.question, self.score)
    
    def color(self):
        if self.score == 0:
            return "red"
        elif self.score == 1:
            return "red"
        elif self.score == 2:
            return "red"
        elif self.score == 3:
            return "pink"
        elif self.score == 4:
            return "green"
        elif self.score == 5:
            return "green"
         

words/views/learn.py
'''
Created on 22-09-2012

@author: pawel
'''

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from words.models import Question
from words.learning import LearningBunch

@login_required
def learn(request, lesson_id = None, days = 0, mode = 'learn'):
    return render_learn_view(request, Question.objects.to_learn_in(request.user, int(days), lesson_id), mode)

@login_required
def repeat(request, mode = 'repeat'):
    return render_learn_view(request, Question.objects.to_repeat(request.user), mode)

def render_learn_view(request, questions_to_learn, mode = "learn"):
    to_learn = map(lambda item: item, questions_to_learn)
    
    import random
    random.shuffle(to_learn)
    
    learning_bunch = LearningBunch(to_learn, mode)
    
    request.session['learning_bunch'] = learning_bunch
    
    return render(request, "learn/learn.html", {'learning_bunch': learning_bunch})

@login_required
def ask_question(request):
    learning_bunch = request.session.get('learning_bunch', None)
    question = learning_bunch.current_question()
    
    return render(request, "learn/next_question.html", {'learning_bunch': learning_bunch, 'question': question})

@login_required
def check(request):
    answer = request.POST['answer']
    
    learning_bunch = request.session.get('learning_bunch', None)
    question = learning_bunch.current_question()
    
    result = learning_bunch.check(answer)
    
    return render(request, "learn/check.html", {'result': result, 'learning_bunch': learning_bunch, 'question': question})

@login_required
def score(request, score):
    learning_bunch = request.session.get('learning_bunch', None)
    
    scored_question = learning_bunch.score_question(int(score))
    question = learning_bunch.next_question()
    
    request.session.modified = True
    
    if question:
        return render(request, "learn/next_question.html", {'learning_bunch': learning_bunch, 'question': question, 'scored_question': scored_question})
    else:
        return render(request, "learn/end.html", {'learning_bunch': learning_bunch, 'scored_question': scored_question})

templates/words/lesson_details.html
{% extends "base.html" %}

{% load url from future %}
{% load templates %}

{% block preload_css %}
	<style>
		#question_frame{
			vertical-align: top;
			padding-left: 10px;
		}
		
	</style>
{% endblock %}

{% block preload_js %}
	<script>
		function show_question_form(){
			$("#question_frame").load("{% url 'words.views.manage.question_new_tile' %}", 
					function(responseText, status, request) {
  						if(request.status != 200){
  							alert('Can\'t show question form. Try again...');
  						}
  						else{
  							$("#id_question").focus();
  						}
  					}
  			);
		}
		
		function show_question_details(question_id){
			url = "{% url 'words.views.manage.question_details_tile' '000' %}";
			url = url.replace('000', question_id);
			
			$("#question_frame").load(url, 
					function(responseText, status, request) {
  						if(request.status != 200){
  							alert('Can\'t show question details. Try again...');
  						}
  					}
  			);
		}
		
		function add_question(){
			form_inputs = {} 
			$("form#question_form input").filter(function(index){
				return this.id.match(/^id_/)
			}).each(function(index){
				form_inputs[this.name] = this.value;	
			});
			
			$("#question_frame").load("{% url 'words.views.manage.question_new_tile' %}",
					form_inputs,
					function(responseText, status, request) {
  						if(request.status != 200){
  							alert('Can\'t show question details Try again...');
  						}
  					}
  			);
		}
		
		function add_answer_row(answer_idx){
			idx = answer_idx + 1
			$("#answer_row_"+idx).show();
			$("#answer_more_"+answer_idx).hide();
	    }
	</script>
{% endblock %}

{% block extra-menu %}
	<a href="javascript:show_question_form()">Add question</a>
	<a href="{% url 'words.views.manage.lesson_list' %}">Back</a>
{% endblock %}

{% block content %}
	<table style="width: 100%;">
		<tr>
			<td style="width: 50%; vertical-align: top;">
				<h3>Lesson: <b>{{lesson.name}}</b></h3>
				<div class="small">
					<table class="model">
						<tr>
							<td class="header">Created:</td>
							<td>{{ lesson.created_at|timesince }} ago</td>
						</tr>
						<tr>
							<td class="header">Questions:</td>
							<td class="right">{{ lesson.question_count}}</td>
						</tr>
						<tr>
							<td class="header">To learn:</td>
							<td class="right">{{ lesson.question_to_learn_count}}</td>
						</tr>
					</table>
				</div>
				
				<br/>
				<h3>Questions</h3>
				<div class="pagination">
				    <span class="step-links">
				        {% if question_page.has_previous %}
				            <a href="?page={{ question_page.previous_page_number }}">previous</a>
				        {% endif %}
				
				        <span class="current">
				            Page {{ question_page.number }} of {{ question_page.paginator.num_pages }}.
				        </span>
				
				        {% if question_page.has_next %}
				            <a href="?page={{ question_page.next_page_number }}">next</a>
				        {% endif %}
				    </span>
				</div>
			    <table class="model full_width">
			    	<tr>
			    		<th>Question</th>
			    		<th>Answers</th>
			    		<th>Level</th>
			    		<th>Next repeat</th>
			    	</tr>
			        {% for question in question_page.object_list %}
			        	<tr>
			            	<td><a href="javascript:show_question_details('{{question.id}}')">{{ question.question|truncatewords:5 }}</a></td>
			            	<td>
			            		{% for answer in question.answers %}
									{{answer.answer|truncatewords:5}}<br/>
								{% endfor %}	
			            	</td>
			            	<td>{{question.level}}</td>
			            	<td>
			            		{% if question.next_repeat|date_before_today %}
			            			now!
			            		{% else %}
			            			{{question.next_repeat|days_from_now}}
			            		{% endif %}
			            	</td>
			            </tr>
			        {% endfor %}
			    </table>
			</td>
			<td id="question_frame" style="width: 50%;">
			
			</td>
		</tr>
	</table>
{% endblock %}

templates/words/lesson_form.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
	<form method="post" action="{% url 'words.views.manage.new_lesson' %}">
		<table class="model">
			{{form.as_table}}
		</table>
		<input type="submit" value="Create lesson" />
	</form>
{% endblock %}

templates/words/lesson_list.html
{% extends "base.html" %}

{% load url from future %}

{% block extra-menu %}
	<a href="{% url 'words.views.manage.new_lesson' %}">New</a>
{% endblock %}

{% block content %}
	<h3>Lessons</h3>
    <table class="model">
    	<tr>
    		<th>Name</th>
    		<th>Created</th>
    		<th>Question count</th>
    		<th>To learn</th>
    		<th>Active</th>
    	</tr>
        {% for lesson in lessons %}
        	<tr {% if not lesson.active %} class="not_active" {% endif %}>
            	<td><a href="{% url 'words.views.manage.lesson_details' lesson.id %}">{{ lesson.name }}</a></td>
            	<td>{{ lesson.created_at|timesince }} ago</td>
            	<td class="right">{{ lesson.question_count }}</td>
            	<td class="right"><a href="{% url 'learn_lesson' lesson.id %}">{{ lesson.question_to_learn_count}}</a></td>
            	<td>{{ lesson.active }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/words/next_question.html
{% extends "minimal.html" %}

{% load url from future %}
{% load templates %}

{% block content %}
	<div id="content">
		<div style="height: 120px;">&nbsp;</div>
		<div id="question" class="asked_question">
			{{question.question}}
		</div>
		{% if question.question.tip %}
			<div id="asked_question_tip" class="asked_question_tip">
				Tip: {{question.question.tip}}
			</div>
		{% endif %}
		{% if question.question.image_url %}
			<div class="question_img">
				<img src="{{question.question.image_url}}" style="max-height: 250px;"/>
			</div>
		{% endif %}
		<div id="answer_buttons" class="answer_buttons">
			<input type="button" value="    0    " onclick="answered(0)"/>
			<input type="button" value="    1    " onclick="answered(1)"/>
			<input type="button" value="    2    " onclick="answered(2)"/>
			<input type="button" value="    3    " onclick="answered(3)"/>
			<input type="button" value="    4    " onclick="answered(4)"/>
			<input type="button" value="    5    " onclick="answered(5)"/>
		</div>
	</div>
	<div id="js_to_invoke">
		alert('tu');
	</div>
{% endblock %}

templates/words/question_details.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}
	{% include "words/question_details_tile.html" %}
{% endblock %}

templates/words/question_details_tile.html
{% load url from future %}

<table class="model">
	<tr>
		<td class="header">Question:</td>
		<td>{{question.question}}</td>
	</tr>
	<tr>
		<td class="header">Tip:</td>
		<td>{{question.tip}}</td>
	</tr>
	<tr>
		<td class="header">Answer tip:</td>
		<td>{{question.answer_tip}}</td>
	</tr>
	<tr>
		<td class="header">Image url:</td>
		<td>{{question.image_url}}</td>
	</tr>
	<tr>
		<td class="header">Answer image url:</td>
		<td>{{question.answer_image_url}}</td>
	</tr>
	<tr>
		<td class="header">Level:</td>
		<td>{{question.level}}</td>
	</tr>
	<tr>
		<td class="header">E-factor:</td>
		<td>{{question.e_factor}}</td>
	</tr>
	<tr>
		<td class="header">Next repeat:</td>
		<td>{{question.next_repeat}}</td>
	</tr>
	<tr>
		<td class="header">To repeat:</td>
		<td>{{question.to_repeat}}</td>
	</tr>
	<tr>
		<td class="header">Created:</td>
		<td>{{question.created_at|timesince}} ago</td>
	</tr>
</table>

<br/>
<b>Answers:</b>
<table class="model full_width">
	<tr>
		<th>Answer</th>
		<th>Tip</th>
	</tr>
	{% for answer in question.answers %}
		<tr>
			<td>{{answer.answer}}</td>
			<td>{{answer.tip}}</td>
		</tr>
	{% endfor %}		
</table>

<br/>
<b>Levels:</b>
<table class="model full_width">
	<tr>
		<th>Level</th>
		<th>Started</th>
		<th>Day interval</th>
		<th>0</th>
		<th>1</th>
		<th>2</th>
		<th>3</th>
		<th>4</th>
		<th>5</th>
	</tr>
	{% for iteration in question.iterations %}
		<tr>
			<td>{{iteration.level}}</td>
			<td>{{iteration.learning_begin|timesince}} ago</td>
			<td>{{iteration.day_interval}}</td>
			<td>{{iteration.answers_0}}</td>
			<td>{{iteration.answers_1}}</td>
			<td>{{iteration.answers_2}}</td>
			<td>{{iteration.answers_3}}</td>
			<td>{{iteration.answers_4}}</td>
			<td>{{iteration.answers_5}}</td>
		</tr>
	{% endfor %}		
</table>

templates/words/question_form_answer_tile.html
{% load url from future %}
{% load templates %}

<tr id="answer_row_{{idx}}" {% if idx != 0 and answer_form.value|answer_value_is_empty %}style="display: none;"{%endif %}>
	<td>{{answer_form.label}}</td>
	<td style="padding: 0px;">
		<table class="model full_width">
			<tr>
				<td>Answer:</td>
				<td>
					<input class="answer_input" type="text" name="answer{{idx}}_0" id="id_answer{{idx}}_0" {% if answer_form.value %} value="{{answer_form.value|first}}" {% endif %}>
					{% if answer_form.errors %} {{answer_form.errors.as_text}}<br/> {% endif %}
				</td>
			<tr>
			<tr>
				<td>Tip:</td>
				<td><input class="answer_input" type="text" name="answer{{idx}}_1" id="id_answer{{idx}}_1" {% if answer_form.value %} value="{{answer_form.value|slice:'1:2'|first}}" {% endif %}></td>
			<tr>
			<tr>
				<td colspan="2">{% if idx != 9 %} <a id="answer_more_{{idx}}" href="javascript:add_answer_row({{idx}});" class="small">Next answer</a> {% endif %}</td>
			</tr>
		</table>
	</td>
</tr>

templates/words/question_form_tile.html
{% load url from future %}

<form id="question_form" method="post" action="javascript:add_question()">
	<table class="model full_width smaller">
		<tr>
			<td class="header">{{form.question.label}}</td>
			<td>
				{{form.question}}
				{{form.question.errors.as_text}}
			</td>
		</tr>
		<tr>
			<td class="header">{{form.tip.label}}</td>
			<td>
				{{form.tip}}
				{{form.tip.errors.as_text}}
			</td>
		</tr>
		<tr>
			<td class="header">{{form.answer_tip.label}}</td>
			<td>
				{{form.answer_tip}}
				{{form.answer_tip.errors.as_text}}
			</td>
		</tr>
		<tr>
			<td class="header">{{form.image_url.label}}</td>
			<td>
				{{form.image_url}}
				{{form.image_url.errors.as_text}}	
			</td>
		</tr>
		<tr>
			<td class="header">{{form.answer_image_url.label}}</td>
			<td>
				{{form.answer_image_url}}
				{{form.answer_image_url.errors.as_text}}	
			</td>
		</tr>
		{% include "words/question_form_answer_tile.html" with idx=0 answer_form=form.answer0 %}
		{% include "words/question_form_answer_tile.html" with idx=1 answer_form=form.answer1 %}
		{% include "words/question_form_answer_tile.html" with idx=2 answer_form=form.answer2 %}
		{% include "words/question_form_answer_tile.html" with idx=3 answer_form=form.answer3 %}
		{% include "words/question_form_answer_tile.html" with idx=4 answer_form=form.answer4 %}
		{% include "words/question_form_answer_tile.html" with idx=5 answer_form=form.answer5 %}
		{% include "words/question_form_answer_tile.html" with idx=6 answer_form=form.answer6 %}
		{% include "words/question_form_answer_tile.html" with idx=7 answer_form=form.answer7 %}
		{% include "words/question_form_answer_tile.html" with idx=8 answer_form=form.answer8 %}
		{% include "words/question_form_answer_tile.html" with idx=9 answer_form=form.answer9 %}
	</table>
	<input type="submit" value="Add question" />
</form>